import puppeteer from 'puppeteer';
import path from 'path';

(async () => {
    console.log('🚀 Starting Automated Steganography Test...');
    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();
    
    try {
        console.log('🌐 Navigating to http://localhost:5173...');
        await page.goto('http://localhost:5173');
        
        console.log('🖼️ Uploading test image...');
        const fileInput = await page.$('input[type="file"]');
        // Path to the dummy image generated by the AI
        const imagePath = 'C:\\Users\\M Fauzan Lubada\\.gemini\\antigravity-ide\\brain\\68b4e420-fe5c-4fbb-b7c7-d974bd1f654b\\dummy_test_image_1782027399777.png';
        await fileInput.uploadFile(imagePath);

        console.log('📝 Setting secret message...');
        const textarea = await page.$('textarea');
        await textarea.click({ clickCount: 3 }); // Select all
        await textarea.type('PESAN SANGAT RAHASIA DARI AUTOMATED TEST!');

        console.log('⚙️ Clicking "Jalankan Eksperimen"...');
        const buttons = await page.$$('button');
        let runButton = null;
        for (const btn of buttons) {
            const text = await page.evaluate(el => el.textContent, btn);
            if (text && text.includes('Jalankan Eksperimen')) {
                runButton = btn;
                break;
            }
        }
        
        if (!runButton) throw new Error("Button not found!");
        await runButton.click();

        console.log('⏳ Waiting for processing to complete...');
        // Wait until PSNR or Ringkasan Metrik appears
        await page.waitForSelector('h2', { text: 'Ringkasan Metrik' });
        await new Promise(r => setTimeout(r, 1000)); // wait a bit for rendering

        // Read PSNR
        const psnrElement = await page.evaluate(() => {
            const elements = Array.from(document.querySelectorAll('div'));
            const psnrLabel = elements.find(el => el.textContent === 'PSNR');
            return psnrLabel ? psnrLabel.nextElementSibling?.textContent : null;
        });

        // Read Integrity
        const integrityElement = await page.evaluate(() => {
            const spans = Array.from(document.querySelectorAll('span'));
            const integritySpan = spans.find(span => span.textContent?.includes('Integrity:'));
            return integritySpan ? integritySpan.textContent : null;
        });

        console.log('✅ TEST PASSED SUCCESSFULLY!');
        console.log('📊 PSNR Achieved:', psnrElement);
        console.log('🔒 Integrity Status:', integrityElement);

    } catch (err) {
        console.error('❌ TEST FAILED:', err);
    } finally {
        await browser.close();
    }
})();
